server:
  port: 9003
spring:
  application:
    name: microservice-movie
eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url:  # 客户端注册地址
      defaultZone: http://127.0.0.1:8888/eureka,http://127.0.0.1:9999/eureka
    registry-fetch-interval-seconds: 5 #获取注册信息的间隔时间  默认30秒

# 修改Ribbon的负载均衡算法
microservice-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #默认是轮询算法

# 开启Hystrix
feign:
  hystrix:
    enabled: true

